### ISSUE TITLE
Ability to export underlying data that built the chart 

### ISSUE THREAD

**Issue by awjrichards** [wmde/phragile#103]
* Allows power users to generate alternative graphs
* Could be CSV format, or new vega graphs format (used by wiki graphs), which I believe is JSON
* NOT A DIFFICULT CHANGE
* See proposed JSON output below

**Comment by awjrichards** [comment]
== Sample JSON output ==
The following is compatible with the new Graph Extension: https://www.mediawiki.org/wiki/Extension:Graph/Demo

[
         {  "date": "2015-02-25", "scope":25, "done":0 },
         {  "date": "2015-02-26", "scope":35, "done":5 },
         {  "date": "2015-02-27", "scope":30, "done":9 },
         {  "date": "2015-02-28", "scope":30, "done":18 },
         {  "date": "2015-03-01", "scope":28, "done":22 },
         {  "date": "2015-03-02", "scope":28, "done":27 }
]
              
Where "scope" is the sum of story points of *all* tasks in the project, as of that date, and "done" is the sum of story points of non-open tasks in the project, as of that date.

**Comment by awjrichards** [comment]
Note this was copied from http://etherpad.wikimedia.org/p/Phragile-requirements-2015-05

**Comment by awjrichards** [comment]
This is a 'must have' for the WMF

**Comment by tobijat** [comment]
To realize this, all project transactions need to be retrieved via conduit and processed which is currently not possible because there is no such conduit method and it would be a rather expensive query.

An alternative solution would be to use data from daily sprint-snapshots in Phragile. They would contain all the necessary data to produce these exports. This could probably be done with not too much effort.

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T100184
